### PR TITLE
Added Max Feathers and Feather Regeneration attributes.

### PR DESCRIPTION
**Pull request by BookerCatch**
Added vanilla-style attributes for Max Feathers and Feather Regeneration. Syncs to capability values. 
Feathers overlay now fades in and out when full (configurable).

### CODE REVIEW

**Comment by ElenaiDev** [comment]
These changes look amazing! Thank you so much and well done BookerCatch.
I will be back at my computer at the end of the week and will be able to overview and merge, and to upload with full credit. Thank you :)

**Comment by BookerCatch** [comment]
Thank you for the kind words! It means a lot. And kudos to you for your fantastic mod.

**Comment by ElenaiDev** [comment]
Absolutely phenomenal work. I love everything you've done, thank you so much! I'll merge now and release later on :)

**Comment by Inf0214** [comment]
Would you kindly add these changes to the 1.18.2 version of the mod too? I would be over the moon it was possible!

**Comment by zengin11** [comment]
I know this is an old thread, but is there any chance that these attribute changes will be ported to 1.18? That would be super helpful

**Pull request merged**
